name: Build WASM object

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: wasm-pack build

      - uses: olegtarasov/get-tag@v2.1.4
        id: tagName
      
      - name: Zip assets
        run: |
          zip -r "lingua-wasm-v${GIT_TAG_NAME}.zip" pkg/lingua_wasm_bg.wasm pkg/lingua_wasm_bg.wasm.d.ts pkg/lingua_wasm.d.ts pkg/lingua_wasm.js mod.ts src/worker.js

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes "v${GIT_TAG_NAME}" "lingua-wasm-v${GIT_TAG_NAME}.zip"